const gymData = 

{
    "businesses": [
        {
            "id": "PN1k_53s-BsSSmMU2KIIzw",
            "alias": "fit-factory-fitness-toronto-4",
            "name": "Fit Factory Fitness",
            "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/pvP9ND1b7BDwpEVAnQ0dCg/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/fit-factory-fitness-toronto-4?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 43,
            "categories": [
                {
                    "alias": "healthtrainers",
                    "title": "Trainers"
                },
                {
                    "alias": "gyms",
                    "title": "Gyms"
                },
                {
                    "alias": "boxing",
                    "title": "Boxing"
                }
            ],
            "rating": 4.0,
            "coordinates": {
                "latitude": 43.6456987028643,
                "longitude": -79.3930924221713
            },
            "transactions": [],
            "location": {
                "address1": "373 King Street West",
                "address2": "",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5V 1K1",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "373 King Street West",
                    "Toronto, ON M5V 1K1",
                    "Canada"
                ]
            },
            "phone": "+14169000362",
            "display_phone": "+1 416-900-0362",
            "distance": 3192.4252271332894
        },
        {
            "id": "VTZ4Ef8aiRWPoBz5BoR8Kg",
            "alias": "university-of-toronto-athletic-centre-toronto",
            "name": "University of Toronto Athletic Centre",
            "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/4jyGf3aMoxJwV6KY2XJ0yw/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/university-of-toronto-athletic-centre-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 12,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                }
            ],
            "rating": 4.0,
            "coordinates": {
                "latitude": 43.66306,
                "longitude": -79.4014
            },
            "transactions": [],
            "location": {
                "address1": "55 Harbord Street",
                "address2": "",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5S 2W6",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "55 Harbord Street",
                    "Toronto, ON M5S 2W6",
                    "Canada"
                ]
            },
            "phone": "+14169783436",
            "display_phone": "+1 416-978-3436",
            "distance": 1314.5737543348212
        },
        {
            "id": "ntSKnqtecZsGu2QF3BOz9Q",
            "alias": "dwell-gym-toronto",
            "name": "Dwell Gym",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/nDrOAjlm11DqspEgq7d9Kg/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/dwell-gym-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 9,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                }
            ],
            "rating": 4.5,
            "coordinates": {
                "latitude": 43.6633492,
                "longitude": -79.3412933
            },
            "transactions": [],
            "location": {
                "address1": "276 Carlaw Avenue",
                "address2": "Unit 101",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M4M 3L1",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "276 Carlaw Avenue",
                    "Unit 101",
                    "Toronto, ON M4M 3L1",
                    "Canada"
                ]
            },
            "phone": "+14164656200",
            "display_phone": "+1 416-465-6200",
            "distance": 4633.812311826795
        },
        {
            "id": "Erlweso-2lkPlgvPtCYPVw",
            "alias": "equinox-bay-street-toronto-2",
            "name": "Equinox Bay Street",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/gZybus_Mqf9EmyRNKkZdsQ/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/equinox-bay-street-toronto-2?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 27,
            "categories": [
                {
                    "alias": "spas",
                    "title": "Day Spas"
                },
                {
                    "alias": "sports_clubs",
                    "title": "Sports Clubs"
                },
                {
                    "alias": "gyms",
                    "title": "Gyms"
                }
            ],
            "rating": 3.5,
            "coordinates": {
                "latitude": 43.64823,
                "longitude": -79.37952
            },
            "transactions": [],
            "price": "$$$",
            "location": {
                "address1": "199 Bay St",
                "address2": "",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5L 1E2",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "199 Bay St",
                    "Toronto, ON M5L 1E2",
                    "Canada"
                ]
            },
            "phone": "+16474975158",
            "display_phone": "+1 647-497-5158",
            "distance": 3223.935268955928
        },
        {
            "id": "5lQj9C5lw57QZaVVMPIJ3g",
            "alias": "body-soul-fitness-toronto",
            "name": "Body + Soul Fitness",
            "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/M07sXJhj1uqfBRzavb-Djg/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/body-soul-fitness-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 1,
            "categories": [
                {
                    "alias": "healthtrainers",
                    "title": "Trainers"
                },
                {
                    "alias": "gyms",
                    "title": "Gyms"
                }
            ],
            "rating": 5.0,
            "coordinates": {
                "latitude": 43.70458,
                "longitude": -79.40966
            },
            "transactions": [],
            "location": {
                "address1": "378 Eglinton Avenue W",
                "address2": null,
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5N 1A2",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "378 Eglinton Avenue W",
                    "Toronto, ON M5N 1A2",
                    "Canada"
                ]
            },
            "phone": "+14164841500",
            "display_phone": "+1 416-484-1500",
            "distance": 3524.3935223149538
        },
        {
            "id": "bLRpRq2Y7j76JHdDzoIfVQ",
            "alias": "goodlife-fitness-toronto-16",
            "name": "GoodLife Fitness",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/nVCqZ6BnQrDEOavjjb7Baw/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/goodlife-fitness-toronto-16?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 63,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                },
                {
                    "alias": "sports_clubs",
                    "title": "Sports Clubs"
                },
                {
                    "alias": "healthtrainers",
                    "title": "Trainers"
                }
            ],
            "rating": 2.5,
            "coordinates": {
                "latitude": 43.6510967860954,
                "longitude": -79.3785557245511
            },
            "transactions": [],
            "location": {
                "address1": "137 Yonge St",
                "address2": "",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5C 1W6",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "137 Yonge St",
                    "Toronto, ON M5C 1W6",
                    "Canada"
                ]
            },
            "phone": "+14165990430",
            "display_phone": "+1 416-599-0430",
            "distance": 2967.3163901283556
        },
        {
            "id": "n4sAvlNuwwYCe4Dy4pNREg",
            "alias": "planet-fitness-toronto-8",
            "name": "Planet Fitness",
            "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/25gekxHkw3iJ_WN1LyS_og/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/planet-fitness-toronto-8?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 6,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                },
                {
                    "alias": "healthtrainers",
                    "title": "Trainers"
                }
            ],
            "rating": 3.5,
            "coordinates": {
                "latitude": 43.66061,
                "longitude": -79.38399
            },
            "transactions": [],
            "location": {
                "address1": "444 Yonge St Units G1 and G4",
                "address2": "",
                "address3": null,
                "city": "Toronto",
                "zip_code": "M5B 2H4",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "444 Yonge St Units G1 and G4",
                    "Toronto, ON M5B 2H4",
                    "Canada"
                ]
            },
            "phone": "+14373757005",
            "display_phone": "+1 437-375-7005",
            "distance": 1876.894035252373
        },
        {
            "id": "1YNONDlsPqeV26qWPfigjg",
            "alias": "toronto-athletic-club-toronto",
            "name": "Toronto Athletic Club",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/S09C2PcSAUcahVVGeF0b7g/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/toronto-athletic-club-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 9,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                }
            ],
            "rating": 5.0,
            "coordinates": {
                "latitude": 43.64663,
                "longitude": -79.38114
            },
            "transactions": [],
            "location": {
                "address1": "79 Wellington Street W",
                "address2": "36th Floor",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5K 1J5",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "79 Wellington Street W",
                    "36th Floor",
                    "Toronto, ON M5K 1J5",
                    "Canada"
                ]
            },
            "phone": "+14168650900",
            "display_phone": "+1 416-865-0900",
            "distance": 3323.4375679656073
        },
        {
            "id": "9kSFs4ChDfTd2Bp7E8118g",
            "alias": "adelaide-club-toronto",
            "name": "Adelaide Club",
            "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/9DFD8R_Bw7jS7x2cFDiX6w/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/adelaide-club-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 12,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                }
            ],
            "rating": 4.0,
            "coordinates": {
                "latitude": 43.64935321259016,
                "longitude": -79.38195254959128
            },
            "transactions": [],
            "location": {
                "address1": "1 First Canadian Place",
                "address2": "",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5X 1B8",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "1 First Canadian Place",
                    "Toronto, ON M5X 1B8",
                    "Canada"
                ]
            },
            "phone": "+14163679957",
            "display_phone": "+1 416-367-9957",
            "distance": 3018.944483306755
        },
        {
            "id": "LeLMbMQFuMbwwNKAbHERWw",
            "alias": "fortis-fitness-toronto-2",
            "name": "Fortis Fitness",
            "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/sqbXuRRYFH7_KZ_RfyB7hA/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/fortis-fitness-toronto-2?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 11,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                }
            ],
            "rating": 4.5,
            "coordinates": {
                "latitude": 43.656399345377984,
                "longitude": -79.33683780212371
            },
            "transactions": [],
            "location": {
                "address1": "11 Carlaw Avenue",
                "address2": "Units 1-3",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M4M 2R7",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "11 Carlaw Avenue",
                    "Units 1-3",
                    "Toronto, ON M4M 2R7",
                    "Canada"
                ]
            },
            "phone": "+14164654777",
            "display_phone": "+1 416-465-4777",
            "distance": 5218.465222029552
        },
        {
            "id": "sWQoKls_fsgh_5lYrVeroA",
            "alias": "rosedale-club-toronto",
            "name": "Rosedale Club",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/xN3QVPkT5l3G0Z6KqImX-g/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/rosedale-club-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 5,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                }
            ],
            "rating": 2.5,
            "coordinates": {
                "latitude": 43.6740965,
                "longitude": -79.389084
            },
            "transactions": [],
            "location": {
                "address1": "920 Yonge Street",
                "address2": "Suite 1",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M4W 3C7",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "920 Yonge Street",
                    "Suite 1",
                    "Toronto, ON M4W 3C7",
                    "Canada"
                ]
            },
            "phone": "+14164791080",
            "display_phone": "+1 416-479-1080",
            "distance": 622.5133712084514
        },
        {
            "id": "3VQNttKUyr2jP-gzmef9nw",
            "alias": "pure-fitness-toronto-2",
            "name": "Pure Fitness",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/CFK7OVN_x1UZ4DE1Vf0Q1A/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/pure-fitness-toronto-2?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 5,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                }
            ],
            "rating": 4.0,
            "coordinates": {
                "latitude": 43.6419567,
                "longitude": -79.3809067
            },
            "transactions": [],
            "location": {
                "address1": "1 York Street",
                "address2": null,
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5J 0C6",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "1 York Street",
                    "Toronto, ON M5J 0C6",
                    "Canada"
                ]
            },
            "phone": "+14164293700",
            "display_phone": "+1 416-429-3700",
            "distance": 3888.598548922967
        },
        {
            "id": "BQ3ggY_559ksJ9hO0fiGQw",
            "alias": "united-boxing-club-toronto-2",
            "name": "United Boxing Club",
            "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/tOo3YJAadZlgZ3bctf5XMw/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/united-boxing-club-toronto-2?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 8,
            "categories": [
                {
                    "alias": "boxing",
                    "title": "Boxing"
                }
            ],
            "rating": 5.0,
            "coordinates": {
                "latitude": 43.66088,
                "longitude": -79.43189
            },
            "transactions": [],
            "location": {
                "address1": "1034 Bloor Street W",
                "address2": "",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M6H 1M3",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "1034 Bloor Street W",
                    "Toronto, ON M6H 1M3",
                    "Canada"
                ]
            },
            "phone": "+14162680696",
            "display_phone": "+1 416-268-0696",
            "distance": 3193.4538516482885
        },
        {
            "id": "DnM2LTTNofqv_UHogQKWqQ",
            "alias": "bang-fitness-toronto",
            "name": "Bang Fitness",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/boxtlvtvMhQPE69tvKxc3Q/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/bang-fitness-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 17,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                },
                {
                    "alias": "healthtrainers",
                    "title": "Trainers"
                }
            ],
            "rating": 4.5,
            "coordinates": {
                "latitude": 43.6470691934052,
                "longitude": -79.4049525260925
            },
            "transactions": [],
            "location": {
                "address1": "610 Queen Street W",
                "address2": "2nd Floor",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M6J 1E3",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "610 Queen Street W",
                    "2nd Floor",
                    "Toronto, ON M6J 1E3",
                    "Canada"
                ]
            },
            "phone": "+14167772264",
            "display_phone": "+1 416-777-2264",
            "distance": 3095.829985628705
        },
        {
            "id": "Or4_p19mJO8Ux9lWVbHyHQ",
            "alias": "la-fitness-toronto-4",
            "name": "LA Fitness",
            "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/eD-aaVopTHAnQFzgyersuQ/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/la-fitness-toronto-4?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 20,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                },
                {
                    "alias": "healthtrainers",
                    "title": "Trainers"
                },
                {
                    "alias": "yoga",
                    "title": "Yoga"
                }
            ],
            "rating": 2.5,
            "coordinates": {
                "latitude": 43.66747672098202,
                "longitude": -79.4649871569431
            },
            "transactions": [],
            "location": {
                "address1": "43 Junction Road",
                "address2": "",
                "address3": null,
                "city": "Toronto",
                "zip_code": "M6N 1B5",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "43 Junction Road",
                    "Toronto, ON M6N 1B5",
                    "Canada"
                ]
            },
            "phone": "+14378881139",
            "display_phone": "+1 437-888-1139",
            "distance": 5534.599729325485
        },
        {
            "id": "bGagIZplZjCaxMQm0131mg",
            "alias": "hone-fitness-toronto",
            "name": "Hone Fitness",
            "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/I2jDmhjyomIq8tGH2IiceQ/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/hone-fitness-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 56,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                }
            ],
            "rating": 3.5,
            "coordinates": {
                "latitude": 43.6676599,
                "longitude": -79.3852464
            },
            "transactions": [],
            "location": {
                "address1": "7 Isabella Street",
                "address2": "",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M4Y 1M7",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "7 Isabella Street",
                    "Toronto, ON M4Y 1M7",
                    "Canada"
                ]
            },
            "phone": "+14164999966",
            "display_phone": "+1 416-499-9966",
            "distance": 1186.885035560805
        },
        {
            "id": "-EjeybJYy_8fY2IQBjTWrQ",
            "alias": "kx-yorkville-toronto",
            "name": "KX Yorkville",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/6c0SInywNWC9U1xUmK-7IA/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/kx-yorkville-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 10,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                },
                {
                    "alias": "chiropractors",
                    "title": "Chiropractors"
                },
                {
                    "alias": "healthtrainers",
                    "title": "Trainers"
                }
            ],
            "rating": 5.0,
            "coordinates": {
                "latitude": 43.6741851,
                "longitude": -79.3980702
            },
            "transactions": [],
            "location": {
                "address1": "263 Davenport Road",
                "address2": "",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5R 1J9",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "263 Davenport Road",
                    "Toronto, ON M5R 1J9",
                    "Canada"
                ]
            },
            "phone": "+14169269757",
            "display_phone": "+1 416-926-9757",
            "distance": 101.11684508357222
        },
        {
            "id": "J0r3pU8KHfLKBe7jIIK0Rw",
            "alias": "equinox-yorkville-toronto-2",
            "name": "Equinox Yorkville",
            "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/2CG9Moly9REwjcnFK9fUKQ/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/equinox-yorkville-toronto-2?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 25,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                },
                {
                    "alias": "sports_clubs",
                    "title": "Sports Clubs"
                },
                {
                    "alias": "spas",
                    "title": "Day Spas"
                }
            ],
            "rating": 2.5,
            "coordinates": {
                "latitude": 43.6712,
                "longitude": -79.39436
            },
            "transactions": [],
            "price": "$$$",
            "location": {
                "address1": "55 Avenue Rd",
                "address2": "",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5R 3L2",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "55 Avenue Rd",
                    "Toronto, ON M5R 3L2",
                    "Canada"
                ]
            },
            "phone": "+14169618400",
            "display_phone": "+1 416-961-8400",
            "distance": 342.4122418545128
        },
        {
            "id": "tQMxkKHAuIDTkdwrvyyIbA",
            "alias": "gogo-muscle-training-toronto",
            "name": "GoGo Muscle Training",
            "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/94a_k8pClu9huumxWdTqZA/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/gogo-muscle-training-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 1,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                },
                {
                    "alias": "healthtrainers",
                    "title": "Trainers"
                }
            ],
            "rating": 5.0,
            "coordinates": {
                "latitude": 43.67142,
                "longitude": -79.39087
            },
            "transactions": [],
            "location": {
                "address1": "70 Yorkville Avenue",
                "address2": "Suite MR5",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5R 1B9",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "70 Yorkville Avenue",
                    "Suite MR5",
                    "Toronto, ON M5R 1B9",
                    "Canada"
                ]
            },
            "phone": "+18774404646",
            "display_phone": "+1 877-440-4646",
            "distance": 564.3675965090554
        },
        {
            "id": "-b0H3B8uN4Vz-p6Z1O446g",
            "alias": "goodlife-fitness-toronto-25",
            "name": "GoodLife Fitness",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/9lCz6ZxqarD7kQRe_Xn-NA/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/goodlife-fitness-toronto-25?adjust_creative=-cpDofS3tARbncx17p-yow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-cpDofS3tARbncx17p-yow",
            "review_count": 32,
            "categories": [
                {
                    "alias": "gyms",
                    "title": "Gyms"
                },
                {
                    "alias": "sports_clubs",
                    "title": "Sports Clubs"
                },
                {
                    "alias": "healthtrainers",
                    "title": "Trainers"
                }
            ],
            "rating": 4.0,
            "coordinates": {
                "latitude": 43.6488246,
                "longitude": -79.3919217
            },
            "transactions": [],
            "location": {
                "address1": "267 Richmond Street W",
                "address2": "",
                "address3": "",
                "city": "Toronto",
                "zip_code": "M5V 3M6",
                "country": "CA",
                "state": "ON",
                "display_address": [
                    "267 Richmond Street W",
                    "Toronto, ON M5V 3M6",
                    "Canada"
                ]
            },
            "phone": "+14165911315",
            "display_phone": "+1 416-591-1315",
            "distance": 2858.020076617036
        }
    ],
    "total": 746,
    "region": {
        "center": {
            "longitude": -79.39682006835938,
            "latitude": 43.67428196976998
        }
    }
}

const reviewData =
{
    "reviews": [
        {
            "id": "RwHPaqTXiJUlx34o7b6TXw",
            "url": "https://www.yelp.com/biz/fit-factory-fitness-toronto-4?adjust_creative=-cpDofS3tARbncx17p-yow&hrid=RwHPaqTXiJUlx34o7b6TXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=-cpDofS3tARbncx17p-yow",
            "text": "I've never been here but have been doing their virtual workouts for two straight weeks.  \n\nI like the fact that the classes are quick (30 minutes) and very...",
            "rating": 4,
            "time_created": "2020-04-06 15:40:58",
            "user": {
                "id": "pMefTWo6gMdx8WhYSA2u3w",
                "profile_url": "https://www.yelp.com/user_details?userid=pMefTWo6gMdx8WhYSA2u3w",
                "image_url": "https://s3-media1.fl.yelpcdn.com/photo/jktFpBdsH_oILLBbCjHOkQ/o.jpg",
                "name": "Bernie C."
            }
        },
        {
            "id": "1W9fFYEjqquJTnmIDuefQA",
            "url": "https://www.yelp.com/biz/fit-factory-fitness-toronto-4?adjust_creative=-cpDofS3tARbncx17p-yow&hrid=1W9fFYEjqquJTnmIDuefQA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=-cpDofS3tARbncx17p-yow",
            "text": "I joined Fit Factory in May and decided to stay after my trial. It's been six weeks and I'm so grateful I did it because I haven't felt better in the last...",
            "rating": 5,
            "time_created": "2019-07-13 11:37:48",
            "user": {
                "id": "hIsl1D87ieYF99e0LjaWVA",
                "profile_url": "https://www.yelp.com/user_details?userid=hIsl1D87ieYF99e0LjaWVA",
                "image_url": "https://s3-media3.fl.yelpcdn.com/photo/E8k6OoZLsbxpl4ZjAvjZjw/o.jpg",
                "name": "Kat B."
            }
        },
        {
            "id": "DKHXPys6Rzpz9NryLqTobA",
            "url": "https://www.yelp.com/biz/fit-factory-fitness-toronto-4?adjust_creative=-cpDofS3tARbncx17p-yow&hrid=DKHXPys6Rzpz9NryLqTobA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=-cpDofS3tARbncx17p-yow",
            "text": "I started with a one month trial after struggling to lose weight for a year and lost 10 lbs in that month through a combination of dieting and fit factory...",
            "rating": 5,
            "time_created": "2020-09-02 19:24:31",
            "user": {
                "id": "jW0yGlx2DrgilG7okGOmSA",
                "profile_url": "https://www.yelp.com/user_details?userid=jW0yGlx2DrgilG7okGOmSA",
                "image_url": null,
                "name": "Motaz A."
            }
        }
    ],
    "total": 43,
    "possible_languages": [
        "en"
    ]
}

const dwellData = 

{
    "reviews": [
        {
            "id": "CgOMauo9WIRZOt-mUanjlg",
            "url": "https://www.yelp.com/biz/dwell-gym-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&hrid=CgOMauo9WIRZOt-mUanjlg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=-cpDofS3tARbncx17p-yow",
            "text": "Tried for 3 days to ask someone a couple of questions about memebership and never got any calls returned...doors are locked, no proper info on them...total...",
            "rating": 1,
            "time_created": "2017-11-27 18:29:56",
            "user": {
                "id": "IZ4e7jv-RGOtNSsFlsswMQ",
                "profile_url": "https://www.yelp.com/user_details?userid=IZ4e7jv-RGOtNSsFlsswMQ",
                "image_url": "https://s3-media1.fl.yelpcdn.com/photo/z0Vx45RAHrL1ArHvek0Dsg/o.jpg",
                "name": "L J."
            }
        },
        {
            "id": "PRoj9BfFKChwl3rYJq2OBg",
            "url": "https://www.yelp.com/biz/dwell-gym-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&hrid=PRoj9BfFKChwl3rYJq2OBg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=-cpDofS3tARbncx17p-yow",
            "text": "This is a pretty good independent gym. The owner is on site much of the time, which is cool. \n\nIt took over from Fortis fitness, which moved. There's still...",
            "rating": 5,
            "time_created": "2015-08-04 15:35:21",
            "user": {
                "id": "qp0Ne8Ndhucz7s46GLO0og",
                "profile_url": "https://www.yelp.com/user_details?userid=qp0Ne8Ndhucz7s46GLO0og",
                "image_url": "https://s3-media1.fl.yelpcdn.com/photo/ubzXNABeQHH5tIuP9B6d_g/o.jpg",
                "name": "Michael F."
            }
        },
        {
            "id": "ehH3BTmkC3Q4XXWVu2Ilkw",
            "url": "https://www.yelp.com/biz/dwell-gym-toronto?adjust_creative=-cpDofS3tARbncx17p-yow&hrid=ehH3BTmkC3Q4XXWVu2Ilkw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=-cpDofS3tARbncx17p-yow",
            "text": "I love this gym. It's very convenient as it's open 24/7, and having an access key card and not having to go through a reception makes it a breeze and hassle...",
            "rating": 5,
            "time_created": "2019-06-23 15:22:34",
            "user": {
                "id": "LCr6TlHMhbzvH-KF28-vRA",
                "profile_url": "https://www.yelp.com/user_details?userid=LCr6TlHMhbzvH-KF28-vRA",
                "image_url": null,
                "name": "K S."
            }
        }
    ],
    "total": 9,
    "possible_languages": [
        "en"
    ]
}

const clubData = 

{
    "reviews": [
        {
            "id": "a7bgBWUKqZzHIawdtsj0Qg",
            "url": "https://www.yelp.com/biz/united-boxing-club-toronto-2?adjust_creative=-cpDofS3tARbncx17p-yow&hrid=a7bgBWUKqZzHIawdtsj0Qg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=-cpDofS3tARbncx17p-yow",
            "text": "Needing to add some cardio and a little stress relief to my routine, I was curious about adding boxing fitness.  A couple of months in and I can honestly...",
            "rating": 5,
            "time_created": "2019-05-10 14:36:24",
            "user": {
                "id": "vM65C5n7tMtRmwxlBTfMaw",
                "profile_url": "https://www.yelp.com/user_details?userid=vM65C5n7tMtRmwxlBTfMaw",
                "image_url": "https://s3-media2.fl.yelpcdn.com/photo/pGQIe0u6hix6_4ecXPq27Q/o.jpg",
                "name": "Kara M."
            }
        },
        {
            "id": "sK0YYOy1t3DlQiEDkq88Kw",
            "url": "https://www.yelp.com/biz/united-boxing-club-toronto-2?adjust_creative=-cpDofS3tARbncx17p-yow&hrid=sK0YYOy1t3DlQiEDkq88Kw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=-cpDofS3tARbncx17p-yow",
            "text": "Welcoming club for beginners as well as advanced boxing training. Great instructors - recommend Fred and Louisy's classes.",
            "rating": 5,
            "time_created": "2019-03-28 17:08:04",
            "user": {
                "id": "LUHuOlhVTry3R3iiVjcntg",
                "profile_url": "https://www.yelp.com/user_details?userid=LUHuOlhVTry3R3iiVjcntg",
                "image_url": "https://s3-media2.fl.yelpcdn.com/photo/qBbXFp8Hl0nlV4JmvSXeHQ/o.jpg",
                "name": "Mel A."
            }
        },
        {
            "id": "iWgb3cdUCGjLw124V4NCvA",
            "url": "https://www.yelp.com/biz/united-boxing-club-toronto-2?adjust_creative=-cpDofS3tARbncx17p-yow&hrid=iWgb3cdUCGjLw124V4NCvA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=-cpDofS3tARbncx17p-yow",
            "text": "Very happy to call this gym my new home!!\n\nI have been boxing for 7 years with the same coach, 5 different gyms. I've been in and out of all so many...",
            "rating": 5,
            "time_created": "2014-10-01 11:55:02",
            "user": {
                "id": "TbhyP24zYZqZ2VJZgu1wrg",
                "profile_url": "https://www.yelp.com/user_details?userid=TbhyP24zYZqZ2VJZgu1wrg",
                "image_url": "https://s3-media3.fl.yelpcdn.com/photo/CTwKpougII1Wbyb80xH4JA/o.jpg",
                "name": "Lauren M."
            }
        }
    ],
    "total": 8,
    "possible_languages": [
        "en"
    ]
}

function onPageLoad () {
    document.getElementById("test").innerHTML = gymData.businesses[0].name;
    document.getElementById("test2").innerHTML=`<img class="gym-photo" src="${gymData.businesses[0].image_url}" width="200px" height="330px">`;
    document.getElementById("test3").innerHTML = gymData.businesses[12].name;
    document.getElementById("test4").innerHTML=`<img class="gym-photo" src="${gymData.businesses[12].image_url}" width="200px" height="330px">`;
    document.getElementById("test5").innerHTML = gymData.businesses[2].name;
    document.getElementById("test6").innerHTML=`<img class="gym-photo" src="${gymData.businesses[2].image_url}" width="200px" height="330px">`;
   

    document.getElementById("draft").innerHTML = JSON.stringify(reviewData.reviews[2].text);
    document.getElementById("draft1").innerHTML = JSON.stringify(clubData.reviews[1].text);
    document.getElementById("draft2").innerHTML = JSON.stringify(dwellData.reviews[2].text);
    }


